enum description
enumDecl
	^#(GIT_OK                0
	
	   GIT_ERROR            -1
	   GIT_ENOTFOUND        -3
	   GIT_EEXISTS          -4
	   GIT_EAMBIGUOUS       -5
	   GIT_EBUFS            -6
	   GIT_EUSER            -7
	   GIT_EBAREREPO        -8
	   GIT_EORPHANEDHEAD    -9
	   GIT_EUNMERGED       -10
	   GIT_ENONFASTFORWARD -11
	   GIT_EINVALIDSPEC    -12
	   GIT_EMERGECONFLICT  -13

	   GIT_PASSTHROUGH     -30
	   GIT_ITEROVER        -31)